#ifndef EVENTS_H
#define EVENTS_H

enum Events
{
    NO_EVENT_OCCURRED,
    MENU_BUTTON_PRESSED,
    MENU_BUTTON_LONG_PRESSED,
    TIMER_UP_BUTTON_PRESSED,
    TIMER_DOWN_BUTTON_PRESSED,
    START_BUTTON_PRESSED,
    OVEN_DONE,
    TIMER_TIMEOUT
};

#endif
